version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./srv/nginx/vhost.d:/etc/nginx/vhost.d
      - ./srv/nginx/html:/usr/share/nginx/html
      - ./srv/ssl_certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always

  nginx-lets-encrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - ./srv/ssl_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  api:
    image: judge0/api
    env_file: judge0-api.conf
    environment:
      - VIRTUAL_HOST=api.judge0.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.judge0.com
      - LETSENCRYPT_EMAIL=hermanz.dosilovic@gmail.com
    privileged: true
    restart: always

  worker:
    image: judge0/api
    env_file: judge0-api.conf
    command: rails resque:work
    privileged: true
    restart: always

  db:
    image: postgres
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./srv/redis-data:/data
    restart: always
